apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app.kubernetes.io/instance: insta
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: matomo
    app.kubernetes.io/instance: insta
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-deployment
  labels:
    app.kubernetes.io/component: analytics
    app.kubernetes.io/instance: insta
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: matomo
      app.kubernetes.io/instance: insta
  template:
    metadata:
      labels:
        app.kubernetes.io/name: matomo
        app.kubernetes.io/instance: insta
    spec:
      containers:
        - name: analytics-container-php
          image: matomo:4.2-apache
          ports:
            - name: http
              containerPort: 80
          env:
            - name: MATOMO_DATABASE_ADAPTER
              valueFrom:
                configMapKeyRef:
                  name: shared-config-map
                  key: matomoDatabaseAdapter
            - name: MATOMO_DATABASE_TABLES_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: shared-config-map
                  key: matomoDatabaseTablesPrefix
            - name: MATOMO_DATABASE_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: shared-config-map
                  key: mysqlDatabase
            - name: MATOMO_DATABASE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: mysqlUsername
            - name: MATOMO_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shared-secret
                  key: mysqlPassword
