
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo
  labels:
    app.kubernetes.io/component: echo
    app.kubernetes.io/instance: insta
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: echo
      app.kubernetes.io/instance: insta
  template:
    metadata:
      labels:
        app.kubernetes.io/name: echo
        app.kubernetes.io/instance: insta
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: echo
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http
---
apiVersion: v1
kind: Service
metadata:
  name: echo
  labels:
    app.kubernetes.io/instance: insta
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app.kubernetes.io/name: echo
    app.kubernetes.io/instance: insta
