apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: insta
  labels:
    app.kubernetes.io/instance: insta
  annotations:
    dev.okteto.com/generate-host: "true"
spec:
  rules:
    - http:
        paths:
          - path: /uploads
            backend:
              serviceName: storage-service
              servicePort: 80
          - path: /api
            backend:
              serviceName: api-service
              servicePort: 80
          - path: /
            backend:
              serviceName: frontend-service
              servicePort: 80