name: ci

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./api
          target: admin
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/insta-k8s:admin
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./api
          target: api
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/insta-k8s:api
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}